### PR TITLE
Update to 2022.04.0

### PR DESCRIPTION
**Pull request by ketilmo**
Hi @smarthall,

I have created a pull request that bumps the repository to match the latest upstream release. Let me know if you have comments or questions. Feel free to edit the pull request as desired.

### CODE REVIEW

**Comment by smarthall** [comment]
Awesome. Thanks for saving me the time! :-)

**Comment by ketilmo** [comment]
Only a pleasure, @smarthall! Thanks for creating this great add-in. It's appreciated.

**Comment by ketilmo** [comment]
Hi @smarthall,

I just deployed the upgraded version, and I see the following errors in the log:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/mqtt.py", line 89, in async_publish_payload
    data = data_processor.generate_data()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 160, in generate_data
    output = calculate()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 57, in <lambda>
    DATA_POINT_LIGHTNING: lambda val: calculate_distance(
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/util/distance.py", line 15, in calculate_distance
    return round(value / 1.609, 1)
TypeError: unsupported operand type(s) for /: 'str' and 'float'
INFO:aiohttp.access:192.168.56.130 [19/Apr/2022:08:40:09 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
```

Do you see the same errors at your end? If yes, could this be an issue with the upstream repository?

**Comment by smarthall** [comment]
@ketilmo Do you have the lightning sensor? I do not, and it looks like this error only triggers on lightning sensors. Given they were only just added upstream, I assume that this feature just hasn't been tested enough.

**Comment by smarthall** [comment]
Yup, it looks like `val` on this line https://github.com/bachya/ecowitt2mqtt/blob/dev/ecowitt2mqtt/data.py#L58 should be changed to `float(val)`, and that should fix it.

**Comment by smarthall** [comment]
Raised the issue with upstream: https://github.com/bachya/ecowitt2mqtt/issues/118

**Comment by ketilmo** [comment]
Hi @smarthall,

Thanks for your swift follow up. You are completely correct – I have a lightning sensor and it's probably the reason for the issue. I see that you have already addressed the issue with the upstream repo maintainers, and the problem even seems to be fixed already. Thanks a ton for your efforts, it's appreciated.

**Comment by smarthall** [comment]
FYI: Rlled out the new upstream version here: https://github.com/smarthall/hassio-addons/commit/0c5b685a078b64aa007f46acca39a7f6ae607eba

**Comment by ketilmo** [comment]
Thanks @smarthall,

I got the opportunity to test the fix now. Unfortunately, I get a slightly different error message after the update:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/mqtt.py", line 89, in async_publish_payload
    data = data_processor.generate_data()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 160, in generate_data
    output = calculate()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 57, in <lambda>
    DATA_POINT_LIGHTNING: lambda val: calculate_distance(
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/util/distance.py", line 14, in calculate_distance
    float_value = float(value)
ValueError: could not convert string to float: ''
INFO:aiohttp.access:192.168.56.130 [23/Apr/2022:09:56:50 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
```

I will report this to the upstream repo. Thanks again for your help!

Kind regards,
Ketil

**Pull request merged**
