### PR TITLE
Update to 2022.05.0

### PR DESCRIPTION
**Pull request by ketilmo**
Hi @smarthall,

Here comes a pull request that updates the upstream version to 2022.05.0. Feel free to make edits as desired.

### CODE REVIEW

**Comment by smarthall** [comment]
Sorry for the delay on this one ;-)

**Comment by ketilmo** [comment]
Thanks, Daniel! And no worries. 😊

**Comment by ketilmo** [comment]
@smarthall Heads up: I get the following error after updating: 

`s6-overlay-suexec: fatal: can only run as pid 1`

**Comment by smarthall** [comment]
Yeah I'm getting the same, investigating it now.

**Comment by smarthall** [comment]
Yup, we've hit a bug that was mentioned in the blog post: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Fix coming soon...

**Comment by ketilmo** [comment]
Awesome! Thanks @smarthall!

**Comment by smarthall** [comment]
Fixed in 7b24a226bf17a9a2444f090b4e0ad097d511f29f

**Comment by ketilmo** [comment]
Works like a charm. Thanks again, @smarthall!

**Pull request merged**
